apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      purpose: deployment
  template:
    metadata:
      labels:
        name: nginx
        purpose: deployment
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:stable-alpine3.17-slim
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    name: nginx
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port