apiVersion: v1
kind: Pod
metadata:
  name: gopi-pod-1
  labels:
    name: gopi-pod-1
spec:
  # list of containers
  containers:
  - name: gopi-pod
    image: nginx
    ports:
     - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: gopi-pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - gopi-pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-pod-affinity
    image: nginx
