apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    name: demo
    test: external
spec:
  containers:
  - name: nodeport-pod
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    name: demo
    demo: external
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port
    nodePort: 30007