apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-roboshop
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-efs-dynamic
  labels:
    name: nginx
    purpose: efs-dynamic
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      purpose: efs-dynamic
  template:
    metadata:
      labels:
        name: nginx
        purpose: efs-dynamic
    spec:
      containers:
      - name: nginx-deployment
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
   name: efs-dynamic
spec:
  type: LoadBalancer
  selector:
    demo: efs-dynamic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

