apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    imageReistry: "https://hub.docker.com/"
    app: "roboshop Dev"
spec:
  # list of containers
  containers:
  - name: gopi-pod
    image: nginx
    ports:
     - containerPort: 80