apiVersion: v1
kind: Pod
metadata: 
  name: envar-demo
  labels:
    purpose: practicing-envar
spec:
  containers:
  - name: envar-demo-container
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: hello-amma
      value: "always be happy amma" 