apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod-demo
spec:
  containers:
  - name: demo
    image: nginx
    command: ["sleep","300"]
    ports:
    - containerPort: 80
    env:
    - name: technology
      valueFrom:
        configMapKeyRef:
          name: config-demo
          key: technology
    - name: learner
      valueFrom:
        configMapKeyRef:
          name: config-demo
          key: learner

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod-demo-1
spec:
  containers:
  - name: demo
    image: nginx
    command: ["sleep","300"]
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: config-demo

