apiVersion: v1
kind: Pod
metadata:
  name: secrets-pod-test
spec:
  containers:
  - name: contai
    image: nginx
    command: ["sleep","300"]
    ports:
    - containerPort: 80
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-test
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-test
          key: password
---
apiVersion: v1
kind: Pod
metadata:
  name: secrets-pod-test-1
spec:
  containers:
  - name: contai-1
    image: alpine
    command: ["sleep","100"]  # Corrected "slepp" to "sleep"
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-test
