apiVersion: v1
kind: Pod
metadata:
  name: secrets-pod-test-1
spec:
  containers:
  - name: contai-1
    image: nginx
    command: ["sleep","100"]
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-test